config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts
  mount Commontator::Engine => '/commontator'
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title, :summary, :body, presence: true
  acts_as_commontable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    commontator_thread_show(@post)
  end

  def new
    if cannot? :manage, Post
      redirect_to posts_path, danger: 'У вас нет прав на создание статьи'
    end
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Статья успешно создана'
    else
      render :new, danger: 'Ошибка при создании статьи'
    end
  end

  def edit
    if cannot? :manage, Post
      redirect_to posts_path, danger: 'У вас нет прав на редактирование статьи'
    end
  end

  def update
    if cannot? :manage, Post
      redirect_to posts_path, danger: 'У вас нет прав на изменение статьи'
    end
    if @post.update_attributes(post_params)
      redirect_to @post, notice: 'Статья успешно изменена'
    else
      render :edit, danger: 'Ошибка при изменении статьи'
    end
  end

  def destroy
    if cannot? :manage, Post
      redirect_to posts_path, danger: 'У вас нет прав на удаление статьи' and return
    end
    @post.destroy
    redirect_to posts_path, notice: 'Статья успешно удалена' and return
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image)
  end
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true} do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.submit t('posts.new.save'), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if can? :manage, Post %>
         |
         <%= link_to 'Изменить', edit_post_path(post) %>
         |
         <%= link_to 'Удалить', post_path(post), method: :delete, data: { confirm: 'Вы уверены?' } %>
       <% end %>
    </small>
  </section>

  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>
</article>

app/views/posts/edit.html.erb
<h1><%= t('posts.edit.title') %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= t('posts.index.title') %></h1>
<%= render @posts %>

app/views/posts/new.html.erb
<h1><%= t('posts.new.title') %></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if can? :manage, Post %>
         |
         <%= link_to 'Изменить', edit_post_path(@post) %>
         |
         <%= link_to 'Удалить', post_path(@post), method: :delete, data: { confirm: 'Вы уверены?' } %>
       <% end %>
    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body %>
  </section>
  
  <section class="post-body">
    <%= commontator_thread(@post) %>
  </section>
</article>