config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts
  mount Commontator::Engine => '/commontator'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div class="container">
      <nav class="navbar navbar-light bg-light">
        <ul class="nav navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="<%= posts_path %>">Статьи</a>
          </li>
          <% if can? :manage, Post %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_post_path %>">Новая статья</a>
          </li>
          <% end %>
        </ul>
        <ul class="navbar-nav pull-xs-right">
             <% if user_signed_in? %>
               <li class="nav-item">
                 <% if can? :manage, Post %>
                   Администратор:
                 <% else %>
                   Пользователь:
                 <% end %>
                 <%= current_user.email %>
               </li>
               <li class="nav-item">
                 <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
               </li>
             <% else %>
               <li class="nav-item">
                 <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
               </li>
               <li class="nav-item">
                 <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
               </li>
             <% end %>
           </ul>
      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class ="col-md-12">
          <% flash.each do |name, message| %>
          <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
          <% end %>
        </div>
      </div>

      <%= yield %>
    </div>
  </body>
</html>